# Generated by Django 5.1.7 on 2025-03-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="serial_number",
            field=models.BigIntegerField(),
        ),
    ]
